AppLibrosML/Controllers/LibroController.cs
using System.Drawing.Printing;
using System.Security.Claims;
using AppLibrosML.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppLibrosML.Controllers
{
    public class LibroController : Controller
    {
        public Contexto contexto { get; } //private readonly Contexto contexto; 

        public LibroController(Contexto contexto)
        {
            this.contexto = contexto;
        }

        // Método para obtener el ID del usuario actual
        private int GetUsuarioId()
        {
            return (int)HttpContext.Session.GetInt32("UsuarioId");
        }

        //PARA QUE EL USUARIO CREE EL LIBRO
        // GET: MarcaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MarcaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LibroModelo libro)
        {
            try
            {
                int usuarioId = GetUsuarioId();

                using (var transaction = contexto.Database.BeginTransaction())
                {
                    try
                    {
                        if (string.IsNullOrEmpty(libro.Titulo))
                        {
                            ModelState.AddModelError("Titulo", "El campo título es obligatorio.");

                            // Limpio errores de validación en los campos restantes
                            ModelState.Remove("Autor");
                            ModelState.Remove("Editorial");
                            ModelState.Remove("Comentarios");

                            return View(libro);
                        }
                        libro.Autor = libro.Autor ?? string.Empty;
                        libro.Editorial = libro.Editorial ?? string.Empty;
                        libro.Comentarios = libro.Comentarios ?? string.Empty;

                        contexto.Libros.Add(libro);
                        contexto.SaveChanges();

                        LibrosUsuarioModelo librosUsuario = new LibrosUsuarioModelo()
                        {
                            usuarioID = usuarioId,
                            libroID = libro.ID
                        };

                        contexto.LibrosUsuario.Add(librosUsuario);
                        contexto.SaveChanges();

                        transaction.Commit();

                        return RedirectToAction("UsuarioPerfil", "UsuarioLogin");
                    }
                    catch
                    {
                        transaction.Rollback();
                        throw; 
                    }
                }
            }
            catch
            {
                return View("Create");
            }
        }     

        //Sacar listado de libros según el usuario
        public ActionResult Listado()
        {
            int usuarioId = GetUsuarioId();

            List<LibroModelo> librosUsuario = contexto.LibrosUsuario
                .Where(lu => lu.usuarioID == usuarioId)
                .Select(lu => new LibroModelo
                {
                    ID = lu.libro.ID,
                    Titulo = lu.libro.Titulo ?? string.Empty,
                    Autor = lu.libro.Autor ?? string.Empty,
                    Editorial = lu.libro.Editorial ?? string.Empty,
                    Genero = lu.libro.Genero,
                    Estado = lu.libro.Estado,
                    Comentarios = lu.libro.Comentarios ?? string.Empty,
                    Valoracion = lu.libro.Valoracion
                })
                .ToList();

            return View(librosUsuario);
        }

        // GET: Libro/Edit/5
        public ActionResult Edit(int id)
        {
            var libro = contexto.Libros.FirstOrDefault(l => l.ID == id);

            if (libro == null)
            {
                return NotFound();
            }

            LibroModelo libroModelo = new LibroModelo //Este modelo es el que se mostrará en el edit y sobre el que se edita
            {
                ID = libro.ID,
                Titulo = libro.Titulo ?? string.Empty,
                Autor = libro.Autor ?? string.Empty,
                Editorial = libro.Editorial ?? string.Empty,
                Genero = libro.Genero,
                Estado = libro.Estado,
                Comentarios = libro.Comentarios ?? string.Empty,
                Valoracion = libro.Valoracion
            };

            return View(libroModelo);
        }

        // POST: Libro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, LibroModelo libroActualizado)
        {
            if (id != libroActualizado.ID)
            {
                return NotFound();
            }

            var libro = contexto.Libros.FirstOrDefault(l => l.ID == id);

            if (libro == null)
            {
                return NotFound();
            }

            if (string.IsNullOrEmpty(libroActualizado.Titulo))
            {
                ModelState.AddModelError("Titulo", "El campo título es obligatorio.");

                // Limpio errores de validación en los demás campos
                ModelState.Remove("Autor");
                ModelState.Remove("Editorial");
                ModelState.Remove("Comentarios");

                return View(libroActualizado);
            }
            libro.Autor = libroActualizado.Autor ?? string.Empty;
            libro.Editorial = libroActualizado.Editorial ?? string.Empty;
            libro.Genero = libroActualizado.Genero;
            libro.Estado = libroActualizado.Estado;
            libro.Comentarios = libroActualizado.Comentarios ?? string.Empty;
            libro.Valoracion = libroActualizado.Valoracion;

            contexto.SaveChanges();

            return RedirectToAction("Listado");
        }

        // GET: Libro/Buscador
        public ActionResult Buscador(string searchTerm)
        {
            int usuarioId = GetUsuarioId();

            List<LibroModelo> librosUsuario;

            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                librosUsuario = contexto.LibrosUsuario
                    .Where(lu => lu.usuarioID == usuarioId)
                    .Select(lu => new LibroModelo
                    {
                        ID = lu.libro.ID,
                        Titulo = lu.libro.Titulo ?? string.Empty,
                        Autor = lu.libro.Autor ?? string.Empty,
                        Editorial = lu.libro.Editorial ?? string.Empty,
                        Genero = lu.libro.Genero,
                        Estado = lu.libro.Estado,
                        Comentarios = lu.libro.Comentarios ?? string.Empty,
                        Valoracion = lu.libro.Valoracion
                    })
                    .ToList();
            }
            else
            {
                librosUsuario = contexto.LibrosUsuario
                    .Where(lu => lu.usuarioID == usuarioId && (lu.libro.Titulo.Contains(searchTerm) || lu.libro.Autor.Contains(searchTerm) 
                    || lu.libro.Editorial.Contains(searchTerm) || lu.libro.Genero.Contains(searchTerm) || lu.libro.Estado.Contains(searchTerm)))
                    .Select(lu => new LibroModelo
                    {
                        ID = lu.libro.ID,
                        Titulo = lu.libro.Titulo ?? string.Empty,
                        Autor = lu.libro.Autor ?? string.Empty,
                        Editorial = lu.libro.Editorial ?? string.Empty,
                        Genero = lu.libro.Genero,
                        Estado = lu.libro.Estado,
                        Comentarios = lu.libro.Comentarios ?? string.Empty,
                        Valoracion = lu.libro.Valoracion
                    })
                    .ToList();
            }

            return View("Listado", librosUsuario);
        }



        //NO VA BIEN EL DELETE
        ////GET: Libro/Delete
        //public ActionResult Delete(int id)
        //{
        //    var libro = contexto.Libros.FirstOrDefault(l => l.ID == id);

        //    if (libro == null)
        //    {
        //        return NotFound();
        //    }

        //    LibroModelo libroModelo = new LibroModelo
        //    {
        //        ID = libro.ID,
        //        Titulo = libro.Titulo,
        //        Autor = libro.Autor,
        //        Editorial = libro.Editorial ?? string.Empty,
        //        Genero = libro.Genero,
        //        Estado = libro.Estado,
        //        Comentarios = libro.Comentarios ?? string.Empty,
        //        Valoracion = libro.Valoracion
        //    };

        //    return View(libroModelo);
        //}

        ////POST: Libro/Delete
        //[HttpPost]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    var libro = contexto.Libros.FirstOrDefault(l => l.ID == id);

        //    if (libro == null)
        //    {
        //        return NotFound();
        //    }

        //    var librosUsuario = contexto.LibrosUsuario.Where(lu => lu.libroID == id).ToList();
        //    contexto.LibrosUsuario.RemoveRange(librosUsuario);

        //    contexto.Libros.Remove(libro);
        //    contexto.SaveChanges();

        //    return RedirectToAction("Listado");
        //}

    }
}

AppLibrosML/Controllers/UsuarioLoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Text;
using System.Security.Cryptography;
using AppLibrosML.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace AppLibrosML.Controllers
{
    public class UsuarioLoginController : Controller
    {
        static string cadena = "server=localhost; database=AppLibros; Trusted_Connection=true; MultipleActiveResultSets=true; Encrypt=False";
        public Contexto contexto { get; } //private readonly Contexto contexto; 

        public UsuarioLoginController(Contexto contexto)
        {
            this.contexto = contexto;
        }

        // Método para obtener el ID del usuario actual
        private int GetUsuarioId()
        {
            return (int)HttpContext.Session.GetInt32("UsuarioId");
        }

        //GET:Acceso
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Registrar()
        {
            return View();
        }

        //POST
        [HttpPost]
        public ActionResult Registrar(UsuarioModelo usuario)
        {
            bool registrado;
            string mensaje;

            if (usuario.Contrasenia == usuario.ConfirmarContrasenia)
            {

                usuario.Contrasenia = ConvertirSha256(usuario.Contrasenia);
            }
            else
            {
                ViewData["Mensaje"] = "Las contraseñas no coinciden"; //Con viewdata enviamos datos del cotroller al view
                return View(); //volvemos a la vista
            }

            using (SqlConnection cn = new SqlConnection(cadena))
            {
                //llamar al procedimiento
                SqlCommand cmd = new SqlCommand("registrarUsuario", cn);
                cmd.Parameters.AddWithValue("Correo", usuario.CorreoElectronico);
                cmd.Parameters.AddWithValue("Contrasenia", usuario.Contrasenia);
                cmd.Parameters.Add("Registrado", SqlDbType.Bit).Direction = ParameterDirection.Output;
                cmd.Parameters.Add("Mensaje", SqlDbType.VarChar, 100).Direction = ParameterDirection.Output;
                cmd.CommandType = CommandType.StoredProcedure;

                cn.Open();

                cmd.ExecuteNonQuery();

                registrado = Convert.ToBoolean(cmd.Parameters["Registrado"].Value);
                mensaje = cmd.Parameters["Mensaje"].Value.ToString();


            }

            ViewData["Mensaje"] = mensaje;

            if (registrado)
            {
                return RedirectToAction("Login", "UsuarioLogin");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Login(UsuarioModelo usuario)
        {
            usuario.Contrasenia = ConvertirSha256(usuario.Contrasenia);

            using (SqlConnection cn = new SqlConnection(cadena))
            {

                SqlCommand cmd = new SqlCommand("validarUsuario", cn);
                cmd.Parameters.AddWithValue("Correo", usuario.CorreoElectronico);
                cmd.Parameters.AddWithValue("Contrasenia", usuario.Contrasenia);
                cmd.CommandType = CommandType.StoredProcedure;

                cn.Open();

                usuario.ID = Convert.ToInt32(cmd.ExecuteScalar().ToString());

            }

            if (usuario.ID != 0)
            {
                //Session["usuario"] = usuario;
                HttpContext.Session.SetInt32("UsuarioId", usuario.ID); //guardo id para usarlo en el LibroController
                HttpContext.Session.SetString("usuario", usuario.CorreoElectronico);
                return RedirectToAction("UsuarioPerfil", "UsuarioLogin");
            }
            else
            {
                ViewData["Mensaje"] = "usuario no encontrado";
                return View();
            }
        }

        //ENCRIPTACION DE CONTRASEÑAS
        public static string ConvertirSha256(string texto)
        {
            //using System.Text;
            //USAR LA REFERENCIA DE "System.Security.Cryptography"

            StringBuilder Sb = new StringBuilder();
            using (SHA256 hash = SHA256Managed.Create())
            {
                Encoding enc = Encoding.UTF8;
                byte[] result = hash.ComputeHash(enc.GetBytes(texto));

                foreach (byte b in result)
                    Sb.Append(b.ToString("x2"));
            }

            return Sb.ToString();
        }

        public ActionResult UsuarioPerfil()
        {
            string correoUsuario = HttpContext.Session.GetString("usuario");
            ViewBag.CorreoUsuario = correoUsuario;

            List<LibroModelo> librosLeidos = ObtenerLibrosLeidos();

            return View(librosLeidos);
        }


        // Obtener libros leídos del usuario
        public List<LibroModelo> ObtenerLibrosLeidos()
        {
            int usuarioId = GetUsuarioId();

            List<LibroModelo> librosLeidos = contexto.LibrosUsuario
                .Where(lu => lu.usuarioID == usuarioId && lu.libro.Estado == "Leído")
                .Select(lu => new LibroModelo
                {
                    ID = lu.libro.ID,
                    Titulo = lu.libro.Titulo ?? string.Empty,
                    Autor = lu.libro.Autor ?? string.Empty,
                    Editorial = lu.libro.Editorial ?? string.Empty,
                    Genero = lu.libro.Genero,
                    Estado = lu.libro.Estado,
                    Comentarios = lu.libro.Comentarios ?? string.Empty,
                    Valoracion = lu.libro.Valoracion
                })
                .ToList();

            return librosLeidos;
        }
    }
}

AppLibrosML/Views/UsuarioLogin/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppLibrosML</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppLibrosML.styles.css" asp-append-version="true" />
</head>
<body>
    <section class="vh-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Inicia sesión</p>

                                    <form asp-action="Login" method="post" class="mx-1 mx-md-4">
                                                                        
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="email" name="CorreoElectronico" placeholder="Correo electrónico" class="form-control" />
                                                <label class="form-label" for="form3Example3c">Correo electrónico</label>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="password" name="Contrasenia" placeholder="Contraseña" class="form-control" />
                                                <label class="form-label" for="form3Example4c">Contraseña</label>
                                            </div>
                                        </div>   
                                    
                                        @if (ViewData["Mensaje"] != null){
                                            <div class="alert alert-danger" role="alert">
                                                @ViewData["Mensaje"]
                                            </div>
                                        }
                                    
                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-warning btn-lg">Iniciar Sesión</button>
                                        </div>

                                        <p>¿Todavía no tienes cuenta? <a href="@Url.Action("Registrar","UsuarioLogin")" class="link-info">Regístrate aquí</a></p>

                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://i.pinimg.com/originals/be/9f/41/be9f417ed861b0ce4e4df3106c108d20.jpg"
                                         class="img-fluid" alt="Sample image">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

AppLibrosML/Views/UsuarioLogin/Registrar.cshtml
@{
    ViewData["Title"] = "Registrar";
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppLibrosML</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppLibrosML.styles.css" asp-append-version="true" />
</head>
<body>
    <section class="vh-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Registrarse</p>

                                    <form asp-action="Registrar" method="post" class="mx-1 mx-md-4">

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="email" name="CorreoElectronico" placeholder="Correo electrónico" class="form-control" />
                                                <label class="form-label" for="form3Example3c">Correo electrónico</label>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="password" name="Contrasenia" placeholder="Contraseña" class="form-control" />
                                                <label class="form-label" for="form3Example4c">Contraseña</label>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="password" name="ConfirmarContrasenia" placeholder="Contraseña" class="form-control" />
                                                <label class="form-label" for="form3Example4c">Confirmar Contraseña</label>
                                            </div>
                                        </div>

                                        @if (ViewData["Mensaje"] != null)
                                        {
                                            <div class="alert alert-danger" role="alert">
                                                @ViewData["Mensaje"]
                                            </div>
                                        }

                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-warning btn-lg">Registrarse</button>
                                        </div>

                                        <p>¿Ya tienes una cuenta? <a href="@Url.Action("Login","UsuarioLogin")" class="link-info">Inicia sesión aquí</a></p>

                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://i.pinimg.com/originals/be/9f/41/be9f417ed861b0ce4e4df3106c108d20.jpg"
                                         class="img-fluid" alt="Sample image">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

AppLibrosML/Views/UsuarioLogin/UsuarioPerfil.cshtml
@{
    ViewData["Title"] = "UsuarioPerfil";
}

<section class="h-100 gradient-custom-2">
    <div class="container-fluid">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col">
                <div class="rounded-top text-white d-flex flex-row bg-warning" style="height:200px;">
                    <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                        <img src="https://i.pinimg.com/564x/64/0a/91/640a91892bbe2a38a7e99cc91e1c01e5.jpg" alt="Perfil" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
                    </div>
                    <div class="ms-3" style="margin-top: 130px;">
                        <a asp-area="" asp-controller="Home" asp-action="Logoff" class="btn btn-outline-dark">Cerrar sesión</a>
                        @{
                            var correoUsuario = ViewBag.CorreoUsuario.ToString().Split('@')[0];
                        }
                        <h5>@correoUsuario</h5>
                    </div>
                    <div class="col d-flex align-items-center justify-content-center">
                        <div class="position-relative d-inline-block" style="height: 180px; width: 180px;">
                            <div class="position-absolute top-0 start-0 bottom-0 end-0 rounded-circle border border-4 border-white d-flex flex-column justify-content-center align-items-center">
                                <h4 class="text-center" style="font-size: 18px;">Libros leídos</h4>
                                <h1 class="display-4 text-center" style="font-size: 45px;">@Model.Count</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="row justify-content-center align-items-center mt-5">
                    <div class="col text-center">
                        <a href="@Url.Action("Create", "Libro")" class="btn btn-warning btn-lg">Crear nueva entrada ✏️</a>
                    </div>
                </div>
                <div class="row justify-content-center align-items-center mt-3">
                    <div class="col text-center">
                        <a href="@Url.Action("Listado", "Libro")" class="btn btn-warning btn-lg">Ver mis Libros 📒</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>